### PR TITLE
Emailing

### PR DESCRIPTION
**Pull request by diwakar-s-maurya**
-  add oauth
-  restore this broken feature: redirect to the url which user tried to access before he was not logged in
-  email invites
  We are now not dependent on firebase authorization mechanism, but the code has not been removed yet.

### CODE REVIEW

**Comment by skeep** [comment]
@Mnw2212 could you please have a look at the PR please?

**Comment by mayureshwaykole** [comment]
@diwakar-s-maurya not merging due to email credentials

**Comment by diwakar-s-maurya** [comment]
@skeep How should we manage such code push which have some "project secrets" (API key, SSH key ...)?
Only way i can think of is to make repo private. No outsider has access.
But what if i don't  want all the collaborators to see that "project secret"?

**Comment by skeep** [comment]
Private repo. But collaborator can see.

**Pull request closed without merging**
